version: '3'
services:
  node-app:
    build: .
    ports:
      - "8080:4000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./.env
    # environment:
    #   - PORT=8080